### ISSUE TITLE
Invalid host arch error on M1 Mac

### ISSUE THREAD

**Issue by jerboy** [birros/libmpv-build#21]
When I try to run the "make" command on my M1 Mac, I get the following error message: "Invalid host arch: Your host arch must be amd64 or arm64". My computer is running on an M1 chip, which is arm64-based. It seems like the Makefile is not recognizing the arm64 architecture.

I would appreciate it if you could provide support for M1 Macs in your Makefile. As more and more people switch to M1 Macs, it is becoming increasingly important to have cross-architecture support.

Thank you for your attention to this matter.

**Comment by birros** [comment]
I'm still on an Intel MacBook, so I'm trying to keep this compatibility without having access to a Silicon MacBook.

The lines concerned are:
https://github.com/media-kit/libmpv-darwin-build/blob/b396470423d964786fdfd2116772d37eccfd5e14/Makefile#L31-L37

`aarch64` is probably invalid, can you tell me which arch returns `uname -m`?

**Comment by 23doors** [comment]
On arm macbooks it's `arm64`.

Changing line 33:
```
else ifeq ($(shell uname -m), aarch64)
```
to
```
else ifeq ($(shell uname -m), arm64)
```
seems to fix it and everything else seems to work fine afterwards

**Comment by jerboy** [comment]
```
checking whether we are cross compiling... checking for x86_64-darwin-darwin-strip... no
checking for strip... strip
checking for a race-free mkdir -p... /Users/xxxx/Source/mpv/libmpv-darwin-build/build/tmp/libressl_iossimulator-amd64/src/libressl/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for x86_64-darwin-darwin-cc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling...
```
It still blocking here

**Comment by birros** [comment]
If it freezes, reboot your machine. I think that after a long period of uptime, macOS has problems accessing the sdk.
