### ISSUE TITLE
Support for tvOS

### ISSUE THREAD

**Issue by jerboy** [birros/libmpv-build#24]
Hi there, I'm a big fan of your project and I think it's great. I was wondering if you have any plans to support tvOS in the future? I think it would be a great addition and would love to be able to use your project on my Apple TV. Thank you for your hard work and I look forward to hearing your thoughts on this.

**Comment by birros** [comment]
> Hi there, I'm a big fan of your project and I think it's great. I was wondering if you have any plans to support tvOS in the future?

As mentioned in the README, this repo is primarily for `media-kit`, until Flutter has official tvOS support I don't want to spend time on it.
Also, I don't have an Apple TV (for the moment), so I can't test / debug the builds. Only the simulator is accessible to me.

However, this repo is open to contributions, so if you or anyone else would like to support tvOS, you're welcome.
In theory, as tvOS is very similar to iOS, adding support (modulo scripts to adapt and patches) would start with these two steps:
1. Add:
   - `cross-files/tvos-arm64.ini`
   - `cross-files/tvossimulator-arm64.ini`
   - … (other architectures)
2. Build with the following commands:
    ```shell
    $ make build/output/libmpv-xcframeworks_develop_tvos-arm64-video-default.tar.gz
    $ make build/output/libmpv-xcframeworks_develop_tvossimulator-arm64-video-default.tar.gz
    …
    ```

> Thank you for your hard work and I look forward to hearing your thoughts on this.

❤️

---

I close this issue until a re-evaluation in the future.

**Comment by labulakalia** [comment]
try this https://github.com/DenisovAV/flutter_tv
