### ISSUE TITLE
How to add libmpv?

### ISSUE THREAD

**Issue by kayces** [birros/libmpv-build#27]
I'm currently facing an issue with my Flutter application where some videos are playing without sound. 

To address this, I found some extension libraries https://github.com/media-kit/libmpv-darwin-build/releases
but I'm having trouble understanding how to use these libraries in my Flutter app across Android, iOS, and macOS platforms. I have gone through the provided README.md file, but still, the instructions are not clear to me. 

I would appreciate any guidance or help on how to integrate these extension libraries into my application.

**Comment by birros** [comment]
This repo builds and provides native iOS and macOS libraries for [media_kit](https://pub.dev/packages/media_kit), to use them with your Flutter application please refer to the example provided in the media-kit documentation.

**Comment by kayces** [comment]
> This repo builds and provides native iOS and macOS libraries for [media_kit](https://pub.dev/packages/media_kit), to use them with your Flutter application please refer to the example provided in the media-kit documentation.

I have already reviewed the documentation, but it does not contain any information about integrating libmpv on my own. The documentation also mentions support for the truehd raw TrueHD format, but in reality, it prompts 'Failed to initialize a decoder for codec 'truehd'.' The documentation might be too outdated.

I have scoured through the Github issues, and only this post mentions 'replace the libmpv': https://github.com/media-kit/media-kit/issues/561

However, there are no further explanations.

If you say that this information is in the documentation, could you please provide me with a link? I would be very grateful.

**Comment by birros** [comment]
Sorry, I didn't understand your problem.

Indeed, currently **media-kit** only uses the `default` flavor which contains only the most used codecs.
If you want to get support for all codecs, you'll need the `full` flavor, but unfortunately there's no way of using them "easily" for now.

However, until it becomes available, you can follow this procedure:
- fork [media-kit/media-kit](https://github.com/media-kit/media-kit)
- replace the `*-default.tar.gz` with `*-full.tar.gz` in the iOS and macOS `Makefile`, and the associated `MPV_XCFRAMEWORKS_SHA256SUM`
- redirect the **media-kit** dependencies to your forked repo in your `pubspec.yaml`

**Comment by kayces** [comment]
Thank you very much for your explanation, now I know where to handle these libmpv issues!!

**Comment by andynvt** [comment]
> Sorry, I didn't understand your problem.
> 
> Indeed, currently **media-kit** only uses the `default` flavor which contains only the most used codecs. If you want to get support for all codecs, you'll need the `full` flavor, but unfortunately there's no way of using them "easily" for now.
> 
> However, until it becomes available, you can follow this procedure:
> 
> * fork [media-kit/media-kit](https://github.com/media-kit/media-kit)
> * replace the `*-default.tar.gz` with `*-full.tar.gz` in the iOS and macOS `Makefile`, and the associated `MPV_XCFRAMEWORKS_SHA256SUM`
> * redirect the **media-kit** dependencies to your forked repo in your `pubspec.yaml`

how to add the "full libmpv" like that for android and windows?
