### ISSUE TITLE
How to compile a package containing all references to libmpv on macos?

### ISSUE THREAD

**Issue by klousCan** [birros/libmpv-build#30]
Using libmpv in macOS is a bit complicated and not very friendly for software distribution。
When using macos, always need to use brew to install dependency packages

**Comment by birros** [comment]
If by "all references" you mean "all codecs" in this case, there are already "full" versions that are available. You can download them from the section [/releases](https://github.com/media-kit/libmpv-darwin-build/releases) section.

---

If your question is about `media-kit` I suggest you follow the procedure given in this [comment](https://github.com/media-kit/libmpv-darwin-build/issues/27#issuecomment-1835732250) to use the `full` version.

**Comment by klousCan** [comment]
For example, if there is no ffmpeg library on macos, the application will not be able to use it, so "all references" means including all running dependencies.
例如，如果macos上没有ffmpeg库，应用程序将无法使用它，因此“所有引用”意味着包括运行所需要的依赖项。

**Comment by alexmercerind** [comment]
The binary is self-sufficient. No external dependency.
